TARGET_DIR := .

.PHONY: none
none:

.PHONY: memcpy
memcpy:
	python graph-refine/graph-refine.py graph-refine/seL4-example/$(TARGET_DIR) \
		trace-to:report.txt \
		memcpy

.PHONY: all
all:
	python graph-refine/graph-refine.py graph-refine/seL4-example/$(TARGET_DIR) \
		trace-to:report.txt \
		-exclude \
        	init_freemem \
      	-end-exclude \
		all

.PHONY: StackBounds
StackBounds:
	python graph-refine/graph-refine.py graph-refine/seL4-example/$(TARGET_DIR)
